name: compare gke native actions vs gcloud

on:
  push:
    branches:
      - master

env:
  GKE_CLUSTER: ${{ secrets.GKE_AUTH_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_AUTH_CLUSTER_LOCATION }}

jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_AUTH_SA_KEY_JSON }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true
    - name: get-credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: test-kubectl
      run: |
        pods=$(kubectl get pods -o=jsonpath='{$.items[*]}')
        if [ -n "$pods" ]
        then
            echo "Expected no pods. Got ${pods}"
            exit 1
        fi
  native:
    name: with json creds & kubectl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get-creds
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@add-gke-credentials-actions
      with:
        project_id: ${{ secrets.GKE_AUTH_PROJECT_ID }}
        credentials: ${{ secrets.GKE_AUTH_SA_KEY_JSON }}
        name: ${{ secrets.GKE_AUTH_CLUSTER_NAME }}
        location: ${{ secrets.GKE_AUTH_CLUSTER_LOCATION }}
    - name: test-kubectl
      run: |
        pods=$(kubectl get pods -o=jsonpath='{$.items[*]}')
        if [ -n "$pods" ]
        then
            echo "Expected no pods. Got ${pods}"
            exit 1
        fi
